version: "3.9"

services:
  bot:
    build: .
    container_name: telegram-inline-lyrics-bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GENIUS_ACCESS_TOKEN: ${GENIUS_ACCESS_TOKEN}